In [20]:
import numpy as np
import numpy.random as rd

In [21]:
#ejercicios 11
N=2
A=Matrix([[1,1],[1,0]])
B=Matrix(ZZ, N,N, lambda i,j: 0)
for k in range(1,N+1):
    show("A^",k,"=", A^k)
    B=B+A^k
show("B=",B)

'A^' 1 '=' [1 1]
[1 0]

'A^' 2 '=' [2 1]
[1 1]

'B=' [3 2]
[2 1]

In [22]:
#ejercicios 12
N=3
A=Matrix([[1,0,0],[1,0,1],[1,0,1]])
B=Matrix(ZZ, N,N, lambda i,j: 0)
for k in range(1,N+1):
    show("A^",k,"=", A^k)
    B=B+A^k
show("B=",B)

'A^' 1 '=' [1 0 0]
[1 0 1]
[1 0 1]

'A^' 2 '=' [1 0 0]
[2 0 1]
[2 0 1]

'A^' 3 '=' [1 0 0]
[3 0 1]
[3 0 1]

'B=' [3 0 0]
[6 0 3]
[6 0 3]

In [23]:
#ejercicios 11
N=4
A=Matrix([[0,1,1,0],[0,1,0,1],[0,1,1,1],[1,0,1,1]])
B=Matrix(ZZ, N,N, lambda i,j: 0)
for k in range(1,N+1):
    show("A^",k,"=", A^k)
    B=B+A^k
show("B=",B)

'A^' 1 '=' [0 1 1 0]
[0 1 0 1]
[0 1 1 1]
[1 0 1 1]

'A^' 2 '=' [0 2 1 2]
[1 1 1 2]
[1 2 2 3]
[1 2 3 2]

'A^' 3 '=' [2 3 3 5]
[2 3 4 4]
[3 5 6 7]
[2 6 6 7]

'A^' 4 '=' [ 5  8 10 11]
[ 4  9 10 11]
[ 7 14 16 18]
[ 7 14 15 19]

'B=' [ 7 14 15 18]
[ 7 14 15 18]
[11 22 25 29]
[11 22 25 29]

In [24]:
#ejercicios 11
N=5
A=[[1,1,0,1,1], [1,0,1,0,1], [0,0,1,1,1], 
  [1,1,1,0,1],[1,1,0,1,1]]
A=Matrix(A)
B=Matrix(ZZ, N,N, lambda i,j: 0)
for k in range(1,N+1):
    show("A^",k,"=", A^k)
    B=B+A^k
show("B=",B)

'A^' 1 '=' [1 1 0 1 1]
[1 0 1 0 1]
[0 0 1 1 1]
[1 1 1 0 1]
[1 1 0 1 1]

'A^' 2 '=' [4 3 2 2 4]
[2 2 1 3 3]
[2 2 2 2 3]
[3 2 2 3 4]
[4 3 2 2 4]

'A^' 3 '=' [13 10  7 10 15]
[10  8  6  6 11]
[ 9  7  6  7 11]
[12 10  7  9 14]
[13 10  7 10 15]

'A^' 4 '=' [48 38 27 35 55]
[35 27 20 27 41]
[34 27 20 26 40]
[45 35 26 33 52]
[48 38 27 35 55]

'A^' 5 '=' [176 138 100 130 203]
[130 103  74  96 150]
[127 100  73  94 147]
[165 130  94 123 191]
[176 138 100 130 203]

'B=' [242 190 136 178 278]
[178 140 102 132 206]
[172 136 102 130 202]
[226 178 130 168 262]
[242 190 136 178 278]