In [9]:
import numpy as np
import numpy.random as rd
m = Matrix(RR, 3, lambda i,j: normalvariate(0, 1))
show(m)

[ -0.655194236691713    1.67191145983576 -0.0425552400991927]
[0.00516357389406006  -0.985565485700564   0.333784512376238]
[  0.165255088091142   0.834805973156451   -1.26017471803881]

In [30]:
for k in range(3):
    M=10
    dims=rd.randint(1,4,3)
    m=dims[0]; n=dims[1]; l=dims[2]
    print "\\begin{exmp}"
    print "Encuentre el producto $AB$ de las siguientes matrices"
    A = Matrix(ZZ, m,n, lambda i,j: rd.randint(-M, M))
    B = Matrix(ZZ, n,l, lambda i,j: rd.randint(-M, M))
    print "$$A="+latex(A)+"$$"
    print "$$B="+latex(B)+"$$"
    print "\pause Solución:"
    print "$$AB="+latex(A*B)+"$$"
    print "\end{exmp}"
    print ""

\begin{exmp}
Encuentre el producto $AB$ de las siguientes matrices
$$A= \left(\begin{array}{r}
6 \\
-9 \\
-10
\end{array}\right) $$
$$B= \left(\begin{array}{r}
-5
\end{array}\right) $$
\pause Solución:
$$AB= \left(\begin{array}{r}
-30 \\
45 \\
50
\end{array}\right) $$
\end{exmp}

\begin{exmp}
Encuentre el producto $AB$ de las siguientes matrices
$$A= \left(\begin{array}{r}
2
\end{array}\right) $$
$$B= \left(\begin{array}{rrr}
-1 & 1 & -3
\end{array}\right) $$
\pause Solución:
$$AB= \left(\begin{array}{rrr}
-2 & 2 & -6
\end{array}\right) $$
\end{exmp}

\begin{exmp}
Encuentre el producto $AB$ de las siguientes matrices
$$A= \left(\begin{array}{rr}
-1 & -3 \\
-7 & -1
\end{array}\right) $$
$$B= \left(\begin{array}{r}
-7 \\
-4
\end{array}\right) $$
\pause Solución:
$$AB= \left(\begin{array}{r}
19 \\
53
\end{array}\right) $$
\end{exmp}



In [34]:
for k in range(6):
    M=9
    N=-9
    dims=rd.randint(1,4,3)
    m=dims[0]; n=dims[1]; l=dims[2]
    #print "\\begin{evc}"
    #print "Encuentre el producto $AB$ de las siguientes matrices"
    A = Matrix(ZZ, m,n, lambda i,j: rd.randint(N, M+1))
    B = Matrix(ZZ, n,l, lambda i,j: rd.randint(N, M+1))
    print "\item"
    print "$$A="+latex(A)+"$$"
    print "$$B="+latex(B)+"$$"
    print "\\begin{comment}"
    print "$$AB="+latex(A*B)+"$$"
    print "\end{comment}"
    #print "\end{}"
    print ""

\item
$$A= \left(\begin{array}{r}
5 \\
7 \\
0
\end{array}\right) $$
$$B= \left(\begin{array}{r}
-4
\end{array}\right) $$
\begin{comment}
$$AB= \left(\begin{array}{r}
-20 \\
-28 \\
0
\end{array}\right) $$
\end{comment}

\item
$$A= \left(\begin{array}{rrr}
2 & 7 & 2 \\
8 & -6 & 6
\end{array}\right) $$
$$B= \left(\begin{array}{rr}
6 & 6 \\
-2 & -3 \\
-6 & 8
\end{array}\right) $$
\begin{comment}
$$AB= \left(\begin{array}{rr}
-14 & 7 \\
24 & 114
\end{array}\right) $$
\end{comment}

\item
$$A= \left(\begin{array}{rr}
-4 & -6 \\
0 & 6
\end{array}\right) $$
$$B= \left(\begin{array}{r}
-2 \\
-2
\end{array}\right) $$
\begin{comment}
$$AB= \left(\begin{array}{r}
20 \\
-12
\end{array}\right) $$
\end{comment}

\item
$$A= \left(\begin{array}{r}
7 \\
6
\end{array}\right) $$
$$B= \left(\begin{array}{rr}
-9 & 8
\end{array}\right) $$
\begin{comment}
$$AB= \left(\begin{array}{rr}
-63 & 56 \\
-54 & 48
\end{array}\right) $$
\end{comment}

\item
$$A= \left(\begin{array}{r}
-2 \\
-4
\end{array}\right) $$
$$B